spring:
  # Redis predmemoriranje
  cache:
    type: redis

  # Ru훾na redis konfiguracija
  data:
    redis:
      host: localhost
      port: 6379

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/melodije
    username: admin
    password: admin

  # JPA
  jpa:
    open-in-view: false
    show-sql: true

  # Ograni훾enja veli훾ine API zahtjeva
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 5MB

  # Sesija
  session:
    timeout: 30m

  # Izlaganje javnih resursa na /staticno putanju
  mvc:
    static-path-pattern: /staticno/**

  # Direktorij za spremanje stati훾nih resursa (docker volume)
  web:
    resources:
      # Pripaziti na prava pristupa direktoriju
      # static-locations: file:/var/lib/docker/volumes/spring-data/_data/
      static-locations: file:/tmp/spring-data/

app:
  # Jwt postavke
  jwt:
    tajni-kljuc: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    trajanje: 5s
    davatelj: https://github.com/ttomasicc

  # Spotify API postavke
  spotify:
    base-url: https://api.spotify.com/v1
    client-id: eaae24cbc3624538b796e26024fb64a3
    client-secret: abe0e0a0555c4d6aa238fe9866ecb031

server:
  error:
    include-message: always

logging:
  level:
    org.springframework.security: error
