/*
 * This file is generated by jOOQ.
 */
package com.aimelodije.modeli.generirano;


import com.aimelodije.modeli.generirano.tables.Album;
import com.aimelodije.modeli.generirano.tables.AlbumMelodija;
import com.aimelodije.modeli.generirano.tables.FlywaySchemaHistory;
import com.aimelodije.modeli.generirano.tables.Melodija;
import com.aimelodije.modeli.generirano.tables.Shedlock;
import com.aimelodije.modeli.generirano.tables.Umjetnik;
import com.aimelodije.modeli.generirano.tables.Zanr;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.album</code>.
     */
    public final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.album_melodija</code>.
     */
    public final AlbumMelodija ALBUM_MELODIJA = AlbumMelodija.ALBUM_MELODIJA;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.melodija</code>.
     */
    public final Melodija MELODIJA = Melodija.MELODIJA;

    /**
     * The table <code>public.shedlock</code>.
     */
    public final Shedlock SHEDLOCK = Shedlock.SHEDLOCK;

    /**
     * The table <code>public.umjetnik</code>.
     */
    public final Umjetnik UMJETNIK = Umjetnik.UMJETNIK;

    /**
     * The table <code>public.zanr</code>.
     */
    public final Zanr ZANR = Zanr.ZANR;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Album.ALBUM,
            AlbumMelodija.ALBUM_MELODIJA,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Melodija.MELODIJA,
            Shedlock.SHEDLOCK,
            Umjetnik.UMJETNIK,
            Zanr.ZANR
        );
    }
}
