/*
 * This file is generated by jOOQ.
 */
package com.aimelodije.modeli.generirano;


import com.aimelodije.modeli.generirano.tables.Album;
import com.aimelodije.modeli.generirano.tables.AlbumMelodija;
import com.aimelodije.modeli.generirano.tables.FlywaySchemaHistory;
import com.aimelodije.modeli.generirano.tables.Melodija;
import com.aimelodije.modeli.generirano.tables.Shedlock;
import com.aimelodije.modeli.generirano.tables.Umjetnik;
import com.aimelodije.modeli.generirano.tables.Zanr;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.album</code>.
     */
    public static final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.album_melodija</code>.
     */
    public static final AlbumMelodija ALBUM_MELODIJA = AlbumMelodija.ALBUM_MELODIJA;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.melodija</code>.
     */
    public static final Melodija MELODIJA = Melodija.MELODIJA;

    /**
     * The table <code>public.shedlock</code>.
     */
    public static final Shedlock SHEDLOCK = Shedlock.SHEDLOCK;

    /**
     * The table <code>public.umjetnik</code>.
     */
    public static final Umjetnik UMJETNIK = Umjetnik.UMJETNIK;

    /**
     * The table <code>public.zanr</code>.
     */
    public static final Zanr ZANR = Zanr.ZANR;
}
