/*
 * This file is generated by jOOQ.
 */
package com.aimelodije.modeli.generirano.tables;


import com.aimelodije.modeli.generirano.Keys;
import com.aimelodije.modeli.generirano.Public;
import com.aimelodije.modeli.generirano.tables.records.ZanrRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Zanr extends TableImpl<ZanrRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.zanr</code>
     */
    public static final Zanr ZANR = new Zanr();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ZanrRecord> getRecordType() {
        return ZanrRecord.class;
    }

    /**
     * The column <code>public.zanr.id</code>.
     */
    public final TableField<ZanrRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.zanr.naziv</code>.
     */
    public final TableField<ZanrRecord, String> NAZIV = createField(DSL.name("naziv"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Zanr(Name alias, Table<ZanrRecord> aliased) {
        this(alias, aliased, null);
    }

    private Zanr(Name alias, Table<ZanrRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.zanr</code> table reference
     */
    public Zanr(String alias) {
        this(DSL.name(alias), ZANR);
    }

    /**
     * Create an aliased <code>public.zanr</code> table reference
     */
    public Zanr(Name alias) {
        this(alias, ZANR);
    }

    /**
     * Create a <code>public.zanr</code> table reference
     */
    public Zanr() {
        this(DSL.name("zanr"), null);
    }

    public <O extends Record> Zanr(Table<O> child, ForeignKey<O, ZanrRecord> key) {
        super(child, key, ZANR);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ZanrRecord, Long> getIdentity() {
        return (Identity<ZanrRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ZanrRecord> getPrimaryKey() {
        return Keys.ZANR_PKEY;
    }

    @Override
    public List<UniqueKey<ZanrRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ZANR_NAZIV_KEY);
    }

    @Override
    public Zanr as(String alias) {
        return new Zanr(DSL.name(alias), this);
    }

    @Override
    public Zanr as(Name alias) {
        return new Zanr(alias, this);
    }

    @Override
    public Zanr as(Table<?> alias) {
        return new Zanr(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Zanr rename(String name) {
        return new Zanr(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Zanr rename(Name name) {
        return new Zanr(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Zanr rename(Table<?> name) {
        return new Zanr(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
