/*
 * This file is generated by jOOQ.
 */
package com.aimelodije.modeli.generirano.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Album implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long umjetnikId;
    private final String slika;
    private final String naziv;
    private final LocalDate datumDodano;
    private final String opis;

    public Album(Album value) {
        this.id = value.id;
        this.umjetnikId = value.umjetnikId;
        this.slika = value.slika;
        this.naziv = value.naziv;
        this.datumDodano = value.datumDodano;
        this.opis = value.opis;
    }

    public Album(
        Long id,
        Long umjetnikId,
        String slika,
        String naziv,
        LocalDate datumDodano,
        String opis
    ) {
        this.id = id;
        this.umjetnikId = umjetnikId;
        this.slika = slika;
        this.naziv = naziv;
        this.datumDodano = datumDodano;
        this.opis = opis;
    }

    /**
     * Getter for <code>public.album.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.album.umjetnik_id</code>.
     */
    public Long getUmjetnikId() {
        return this.umjetnikId;
    }

    /**
     * Getter for <code>public.album.slika</code>.
     */
    public String getSlika() {
        return this.slika;
    }

    /**
     * Getter for <code>public.album.naziv</code>.
     */
    public String getNaziv() {
        return this.naziv;
    }

    /**
     * Getter for <code>public.album.datum_dodano</code>.
     */
    public LocalDate getDatumDodano() {
        return this.datumDodano;
    }

    /**
     * Getter for <code>public.album.opis</code>.
     */
    public String getOpis() {
        return this.opis;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Album other = (Album) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.umjetnikId == null) {
            if (other.umjetnikId != null)
                return false;
        }
        else if (!this.umjetnikId.equals(other.umjetnikId))
            return false;
        if (this.slika == null) {
            if (other.slika != null)
                return false;
        }
        else if (!this.slika.equals(other.slika))
            return false;
        if (this.naziv == null) {
            if (other.naziv != null)
                return false;
        }
        else if (!this.naziv.equals(other.naziv))
            return false;
        if (this.datumDodano == null) {
            if (other.datumDodano != null)
                return false;
        }
        else if (!this.datumDodano.equals(other.datumDodano))
            return false;
        if (this.opis == null) {
            if (other.opis != null)
                return false;
        }
        else if (!this.opis.equals(other.opis))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.umjetnikId == null) ? 0 : this.umjetnikId.hashCode());
        result = prime * result + ((this.slika == null) ? 0 : this.slika.hashCode());
        result = prime * result + ((this.naziv == null) ? 0 : this.naziv.hashCode());
        result = prime * result + ((this.datumDodano == null) ? 0 : this.datumDodano.hashCode());
        result = prime * result + ((this.opis == null) ? 0 : this.opis.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Album (");

        sb.append(id);
        sb.append(", ").append(umjetnikId);
        sb.append(", ").append(slika);
        sb.append(", ").append(naziv);
        sb.append(", ").append(datumDodano);
        sb.append(", ").append(opis);

        sb.append(")");
        return sb.toString();
    }
}
