/*
 * This file is generated by jOOQ.
 */
package com.aimelodije.modeli.generirano.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Melodija implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long autorId;
    private final Long zanrId;
    private final String audio;
    private final String naziv;
    private final LocalDate datumDodano;

    public Melodija(Melodija value) {
        this.id = value.id;
        this.autorId = value.autorId;
        this.zanrId = value.zanrId;
        this.audio = value.audio;
        this.naziv = value.naziv;
        this.datumDodano = value.datumDodano;
    }

    public Melodija(
        Long id,
        Long autorId,
        Long zanrId,
        String audio,
        String naziv,
        LocalDate datumDodano
    ) {
        this.id = id;
        this.autorId = autorId;
        this.zanrId = zanrId;
        this.audio = audio;
        this.naziv = naziv;
        this.datumDodano = datumDodano;
    }

    /**
     * Getter for <code>public.melodija.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.melodija.autor_id</code>.
     */
    public Long getAutorId() {
        return this.autorId;
    }

    /**
     * Getter for <code>public.melodija.zanr_id</code>.
     */
    public Long getZanrId() {
        return this.zanrId;
    }

    /**
     * Getter for <code>public.melodija.audio</code>.
     */
    public String getAudio() {
        return this.audio;
    }

    /**
     * Getter for <code>public.melodija.naziv</code>.
     */
    public String getNaziv() {
        return this.naziv;
    }

    /**
     * Getter for <code>public.melodija.datum_dodano</code>.
     */
    public LocalDate getDatumDodano() {
        return this.datumDodano;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Melodija other = (Melodija) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.autorId == null) {
            if (other.autorId != null)
                return false;
        }
        else if (!this.autorId.equals(other.autorId))
            return false;
        if (this.zanrId == null) {
            if (other.zanrId != null)
                return false;
        }
        else if (!this.zanrId.equals(other.zanrId))
            return false;
        if (this.audio == null) {
            if (other.audio != null)
                return false;
        }
        else if (!this.audio.equals(other.audio))
            return false;
        if (this.naziv == null) {
            if (other.naziv != null)
                return false;
        }
        else if (!this.naziv.equals(other.naziv))
            return false;
        if (this.datumDodano == null) {
            if (other.datumDodano != null)
                return false;
        }
        else if (!this.datumDodano.equals(other.datumDodano))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.autorId == null) ? 0 : this.autorId.hashCode());
        result = prime * result + ((this.zanrId == null) ? 0 : this.zanrId.hashCode());
        result = prime * result + ((this.audio == null) ? 0 : this.audio.hashCode());
        result = prime * result + ((this.naziv == null) ? 0 : this.naziv.hashCode());
        result = prime * result + ((this.datumDodano == null) ? 0 : this.datumDodano.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Melodija (");

        sb.append(id);
        sb.append(", ").append(autorId);
        sb.append(", ").append(zanrId);
        sb.append(", ").append(audio);
        sb.append(", ").append(naziv);
        sb.append(", ").append(datumDodano);

        sb.append(")");
        return sb.toString();
    }
}
