/*
 * This file is generated by jOOQ.
 */
package com.aimelodije.modeli.generirano.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Zanr implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String naziv;

    public Zanr(Zanr value) {
        this.id = value.id;
        this.naziv = value.naziv;
    }

    public Zanr(
        Long id,
        String naziv
    ) {
        this.id = id;
        this.naziv = naziv;
    }

    /**
     * Getter for <code>public.zanr.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.zanr.naziv</code>.
     */
    public String getNaziv() {
        return this.naziv;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Zanr other = (Zanr) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.naziv == null) {
            if (other.naziv != null)
                return false;
        }
        else if (!this.naziv.equals(other.naziv))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.naziv == null) ? 0 : this.naziv.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Zanr (");

        sb.append(id);
        sb.append(", ").append(naziv);

        sb.append(")");
        return sb.toString();
    }
}
