/*
 * This file is generated by jOOQ.
 */
package com.aimelodije.modeli.generirano.tables.records;


import com.aimelodije.modeli.generirano.tables.Melodija;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MelodijaRecord extends UpdatableRecordImpl<MelodijaRecord> implements Record6<Long, Long, Long, String, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.melodija.id</code>.
     */
    public MelodijaRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.melodija.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.melodija.autor_id</code>.
     */
    public MelodijaRecord setAutorId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.melodija.autor_id</code>.
     */
    public Long getAutorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.melodija.zanr_id</code>.
     */
    public MelodijaRecord setZanrId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.melodija.zanr_id</code>.
     */
    public Long getZanrId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.melodija.audio</code>.
     */
    public MelodijaRecord setAudio(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.melodija.audio</code>.
     */
    public String getAudio() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.melodija.naziv</code>.
     */
    public MelodijaRecord setNaziv(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.melodija.naziv</code>.
     */
    public String getNaziv() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.melodija.datum_dodano</code>.
     */
    public MelodijaRecord setDatumDodano(LocalDate value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.melodija.datum_dodano</code>.
     */
    public LocalDate getDatumDodano() {
        return (LocalDate) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, String, String, LocalDate> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, String, String, LocalDate> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Melodija.MELODIJA.ID;
    }

    @Override
    public Field<Long> field2() {
        return Melodija.MELODIJA.AUTOR_ID;
    }

    @Override
    public Field<Long> field3() {
        return Melodija.MELODIJA.ZANR_ID;
    }

    @Override
    public Field<String> field4() {
        return Melodija.MELODIJA.AUDIO;
    }

    @Override
    public Field<String> field5() {
        return Melodija.MELODIJA.NAZIV;
    }

    @Override
    public Field<LocalDate> field6() {
        return Melodija.MELODIJA.DATUM_DODANO;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAutorId();
    }

    @Override
    public Long component3() {
        return getZanrId();
    }

    @Override
    public String component4() {
        return getAudio();
    }

    @Override
    public String component5() {
        return getNaziv();
    }

    @Override
    public LocalDate component6() {
        return getDatumDodano();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAutorId();
    }

    @Override
    public Long value3() {
        return getZanrId();
    }

    @Override
    public String value4() {
        return getAudio();
    }

    @Override
    public String value5() {
        return getNaziv();
    }

    @Override
    public LocalDate value6() {
        return getDatumDodano();
    }

    @Override
    public MelodijaRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MelodijaRecord value2(Long value) {
        setAutorId(value);
        return this;
    }

    @Override
    public MelodijaRecord value3(Long value) {
        setZanrId(value);
        return this;
    }

    @Override
    public MelodijaRecord value4(String value) {
        setAudio(value);
        return this;
    }

    @Override
    public MelodijaRecord value5(String value) {
        setNaziv(value);
        return this;
    }

    @Override
    public MelodijaRecord value6(LocalDate value) {
        setDatumDodano(value);
        return this;
    }

    @Override
    public MelodijaRecord values(Long value1, Long value2, Long value3, String value4, String value5, LocalDate value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MelodijaRecord
     */
    public MelodijaRecord() {
        super(Melodija.MELODIJA);
    }

    /**
     * Create a detached, initialised MelodijaRecord
     */
    public MelodijaRecord(Long id, Long autorId, Long zanrId, String audio, String naziv, LocalDate datumDodano) {
        super(Melodija.MELODIJA);

        setId(id);
        setAutorId(autorId);
        setZanrId(zanrId);
        setAudio(audio);
        setNaziv(naziv);
        setDatumDodano(datumDodano);
    }

    /**
     * Create a detached, initialised MelodijaRecord
     */
    public MelodijaRecord(com.aimelodije.modeli.generirano.tables.pojos.Melodija value) {
        super(Melodija.MELODIJA);

        if (value != null) {
            setId(value.getId());
            setAutorId(value.getAutorId());
            setZanrId(value.getZanrId());
            setAudio(value.getAudio());
            setNaziv(value.getNaziv());
            setDatumDodano(value.getDatumDodano());
        }
    }
}
