/*
 * This file is generated by jOOQ.
 */
package com.aimelodije.modeli.generirano.tables.records;


import com.aimelodije.modeli.generirano.tables.Zanr;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZanrRecord extends UpdatableRecordImpl<ZanrRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.zanr.id</code>.
     */
    public ZanrRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.zanr.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.zanr.naziv</code>.
     */
    public ZanrRecord setNaziv(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.zanr.naziv</code>.
     */
    public String getNaziv() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Zanr.ZANR.ID;
    }

    @Override
    public Field<String> field2() {
        return Zanr.ZANR.NAZIV;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNaziv();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNaziv();
    }

    @Override
    public ZanrRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ZanrRecord value2(String value) {
        setNaziv(value);
        return this;
    }

    @Override
    public ZanrRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ZanrRecord
     */
    public ZanrRecord() {
        super(Zanr.ZANR);
    }

    /**
     * Create a detached, initialised ZanrRecord
     */
    public ZanrRecord(Long id, String naziv) {
        super(Zanr.ZANR);

        setId(id);
        setNaziv(naziv);
    }

    /**
     * Create a detached, initialised ZanrRecord
     */
    public ZanrRecord(com.aimelodije.modeli.generirano.tables.pojos.Zanr value) {
        super(Zanr.ZANR);

        if (value != null) {
            setId(value.getId());
            setNaziv(value.getNaziv());
        }
    }
}
